version: '3.3'

services:
   db:
     image: mysql:5.7
     volumes:
       - db_data:/var/lib/mysql
     restart: always
     environment:
       MYSQL_ROOT_PASSWORD: somewordpress
       MYSQL_DATABASE: miblogdb
       MYSQL_USER: soymichel
       MYSQL_PASSWORD: mipass

   miblog:
     depends_on:
       - db
     image: wordpress:latest
     ports:
       - "2500:80"
     restart: always
     environment:
       WORDPRESS_DB_HOST: db:3306
       WORDPRESS_DB_USER: soymichel
       WORDPRESS_DB_PASSWORD: mipass
       WORDPRESS_DB_NAME: miblogdb
volumes:
    db_data: {}